import { NextResponse } from "next/server";

export async function GET(){
              return NextResponse.json([
               {
                id: 0,
                img:"/assets/restaurant/Dev International.avif",
                alt:"Dev International.avif",
                title:"Dev International",
                overlay:"₹100 OFF ABOVE ₹239",
                rating:4.3,
                timing:"50-55",
                food:"North Indian, Chinese, Fast Food, Beverages",
                locality:"Mohan Nagar"
               },
               {
                id: 1,
                img:"/assets/restaurant/jai ganesh.avif",
                alt:"jai ganesh.avif",
                title:"Jai Ganesh Bhojnalaya",
                overlay:"₹150 OFF ABOVE ₹299",
                rating:4,
                timing:"40-45",
                food:"North Indian, South Indian, Indian, Chinese",
                locality:"Bus stand"
               },
               {
                id: 2,
                img:"/assets/restaurant/mr gurug.avif",
                alt:"mr gurug.avif",
                title:"Mr. Gurung Momo & Chinese Corner",
                overlay:"20% OFF UPTO ₹50",
                rating:4.2,
                timing:"40-45",
                food:"Momos, Chinese, Fast Food",
                locality:"Mohan Nagar"
               },
               {
                id: 3,
                img:"/assets/restaurant/shree naivedyam.avif",
                alt:"shree naivedyam.avif",
                title:"Shree Naivedyam",
                overlay:"10% OFF UPTO ₹50",
                rating:4.2,
                timing:"50-55",
                food:"North Indian, Chinese, South Indian, Pizzas, Beverages",
                locality:"Chhindwara City"
               },
               {
                id: 4,
                img:"/assets/restaurant/accord intl.avif",
                alt:"accord intl.avif",
                title:"Accord International",
                overlay:"",
                rating:4.4,
                timing:"60-65",
                food:"North Indian, South Indian, Continental, Beverages",
                locality:"Vishnu Nagar"
               },
               {
                id: 5,
                img:"/assets/restaurant/hotel sai nath.avif",
                alt:"hotel sai nath.avif",
                title:"Hotel Sai Nath & Sai Restaurant",
                overlay:"FREE ITEM",
                rating:4.3,
                timing:"45-50",
                food:"North Indian, South Indian, Chinese, Beverages, Fast Food, Desserts",
                locality:"Chhindwara Locality"
               },
               {
                id: 6,
                img:"/assets/restaurant/malwa family.avif",
                alt:"malwa family.avif",
                title:"Malwa Family Restaurant",
                overlay:"",
                rating:3.8,
                timing:"40-45",
                food:"Indian",
                locality:"Chhindwara City"
               },
               {
                id: 7,
                img:"/assets/restaurant/champaran.avif",
                alt:"champaran.avif",
                title:"Champaran  Handi Restaurant",
                overlay:"ITEMS AT ₹89",
                rating:4.3,
                timing:"45-50",
                food:"North Indian",
                locality:"Nagpur road"
               },
               {
                id: 8,
                img:"/assets/restaurant/apni rasoi.avif",
                alt:"apni rasoi.avif",
                title:"Apni Rasoi Family Dhaba",
                overlay:"",
                rating:4.1,
                timing:"40-45",
                food:"North Indian, Indian, South Indian, Chinese",
                locality:"Parasia Road"
               },
               {
                id: 9,
                img:"/assets/restaurant/bakery world.avif",
                alt:"bakery world.avif",
                title:"Bakery World",
                overlay:"10% OFF ABOVE ₹1099",
                rating:4.3,
                timing:"35-40" ,
                food:"Bakery, Ice Cream, Snacks, Beverages",
                locality:"Parasia Road"
               },
               {
                id: 10,
                img:"/assets/restaurant/adil hotel.avif",
                alt:"adil hotel.avif",
                title:"Adil Hotel",
                overlay:"₹150 OFF ABOVE ₹350",
                rating:4.3,
                timing:"35-40",
                food:"North Indian, Chinese, Fast Food, Beverages",
                locality:"Mohan Nagar"
               },
               {
                id:11,
                img:"/assets/restaurant/thikana.avif",
                alt:"thikana.avif",
                title:"Thikana",
                overlay:"₹50 OFF ABOVE ₹199",
                rating:3.6,
                timing:"50-55",
                food:"Indian",
                locality:"ADARSH NAGAR CHHINDWARA"
               },
               {
                id: 12,
                img:"/assets/restaurant/rangla.avif",
                alt:"rangla.avif",
                title:"Rangla Panjab",
                overlay:"₹100 OFF ABOVE ₹250",
                rating:4.1,
                timing:"45-50",
                food:"North Indian, South Indian, Chinese, Beverages, Fast Food, Desserts",
                locality:"Prasia Road"
               },
               {
                id: 13,
                img:"/assets/restaurant/roof 5.avif",
                alt:"",
                title:"Roof 5",
                overlay:"20% OFF UPTO ₹120",
                rating:4.2,
                timing:"50-55",
                food:"Indian",
                locality:"Chhindwara Locality"
               },
               {
                id: 14,
                img:"/assets/restaurant/28 spice.avif",
                alt:"28 spice.avif",
                title:"28 Spice Club",
                overlay:"",
                rating:4.3,
                timing:"55-60",
                food:"North Indian, South Indian, Chinese, Beverages, Fast Food, Desserts",
                locality:"Chhindwara City"
               },
               {
                id: 15,
                img:"/assets/restaurant/sanju ka dhaba.avif",
                alt:"sanju ka dhaba.avif",
                title:"Sanju Ka Dhaba",
                overlay:"50% OFF UPTO ₹100",
                rating:4.6,
                timing:"45-50",
                food:"North Indian, South Indian, Chinese",
                locality:"Prasia Road"
               },
               {
                id: 16,
                img:"/assets/restaurant/raimen.avif",
                alt:"raimen.avif",
                title:"Raimens Cafe 79",
                overlay:"ITEMS AT ₹49",
                rating:4.3,
                timing:"50-55",
                food:"Bakery, Pizzas, Snacks, Beverages",
                locality:"VIP Road"
               }, 
               {
                id: 17,
                img:"/assets/restaurant/the fusion lounge.avif",
                alt:"the fusion lounge.avif",
                title:"The Fusion Lounge",
                overlay:"10% OFF UPTO ₹40",
                rating:4.1,
                timing:"55-60",
                food:"North Indian, South Indian, Chinese, Beverages, Fast Food, Desserts",
                locality:"Railway Station"
               },
               {
                id: 18,
                img:"/assets/restaurant/the veg legacy.avif",
                alt:"the veg legacy.avif",
                title:"The Veg Legacy",
                overlay:"₹125 OFF ABOVE ₹250",
                rating:4.5,
                timing:"55-60",
                food:"North Indian",
                locality:"Chhindwara City"
               },
               {
                id: 19,
                img:"/assets/restaurant/raajbagh.avif",
                alt:"raajbagh.avif",
                title:"Raajbagh Restaurant",
                overlay:"₹50 OFF ABOVE ₹199",
                rating:3.7,
                timing:"60-65",
                food:"North Indian, South Indian, Indian, Chinese, Fast Food, Beverages",
                locality:"Chhindwara Locality"
               },
               {
                id: 20,
                img:"/assets/restaurant/satkar.avif",
                alt:"satkar.avif",
                title:"Satkar Restaurant",
                overlay:"₹100 OFF ABOVE ₹349",
                rating:4.3,
                timing:"45-50",
                food:"North Indian, South Indian, Indian, Salads, Desserts",
                locality:"Satkar Chowk"
               },
               {
                id: 21,
                img:"/assets/restaurant/momomia.avif",
                alt:"momomia.avif",
                title:"Momomia Love In Every Bite",
                overlay:"₹25% OFF ABOVE ₹149",
                rating:4.3,
                timing:"55-60",
                food:"Momos, Pizzas, Burgers, rolls, Beverages",
                locality:"Chhindwara City"
               },
               {
                id: 22,
                img:"/assets/restaurant/famous Lassi.avif",
                alt:"famous Lassi.avif",
                title:"Famous Lassi Juce Corner",
                overlay:"15% OFF UPTO ₹45",
                rating:4.5,
                timing:"40-45",
                food:"Ice Cream, Desserts, Beverages",
                locality:"Chhindwara Locality"
               },
               {
               id: 23,
               img:"/assets/restaurant/blue chilli.avif",
               alt:"blue chilli.avif",
               title:"Blue Chilli Restaurant",
               overlay:"₹150 OFF ABOVE ₹399",
               rating:4.2,
               timing:"55-60",
               food:"North Indian, South Indian, Indian, Fast Food",
               locality:"Prasia Road"
              },
              {
                id: 24,
                img:"/assets/restaurant/bharat mewad.avif",
                alt:"blue chilli.avif",
                title:"Bharat Mewad Ice Cream",
                overlay:"15% OFF UPTO ₹45",
                rating:4.5,
                timing:"40-45",
                food:"Ice Cream, Desserts, Beverages",
                locality:"Chhindwara Locality"
               },
               {
                id: 25,
                img:"/assets/restaurant/paras mishthan.avif",
                alt:"paras mishthan.avif",
                title:"Paras Mishthan",
                overlay:"20% OFF ABOVE ₹699",
                rating:3.8,
                timing:"50-55",
                food:"Beverages, Sweets, Snacks",
                locality:"Chhindwara City"
               },
               {
                id: 26,
                img:"/assets/restaurant/annus kitchen.avif",
                alt:"annus kitchen.avif",
                title:"Annu's Kitchen's Queen Of Paratha",
                overlay:"10% OFF UPTO ₹40",
                rating:4.5,
                timing:"70-75",
                food:"North Indian, South Indian, Chinese, Beverages, Fast Food, Desserts",
                locality:"Chhindwara City"
               },
               {
                id: 27,
                img:"/assets/restaurant/scoops fast food.avif",
                alt:"scoops fast food.avif",
                title:"Scoops Fast Food And Ice Cream",
                overlay:"",
                rating:4,
                timing:"60-65",
                food:"Bakery, Ice Cream, Snacks, Beverages",
                locality:"Khajri Road"
               },
               {
                id: 28,
                img:"/assets/restaurant/the wood cafe.avif",
                alt:"the wood cafe.avif",
                title:"The Woods Cafe",
                overlay:"",
                rating:false,
                timing:"45-50",
                food:"Chaat, Fast Food, Beverages",
                locality:"Chhindwara City"
               },
               {
                id: 29,
                img:"/assets/restaurant/shirji namkeen.avif",
                alt:"shirji namkeen.avif",
                title:"Shriji Namkeen",
                overlay:"",
                rating:3.9,
                timing:"50-55",
                food:"Snacks, Beverages, Desserts",
                locality:"Chhindwara City"
               },
               {
                id: 30,
                img:"/assets/restaurant/thikana special.avif",
                alt:"thikana special.avif",
                title:"Thikana Special",
                overlay:"₹50 OFF ABOVE ₹199",
                rating:4.7,
                timing:"60-65",
                food:"North Indian, Chinese, Biryani, Sweets, Salads",
                locality:"Chhindwara City"
               },{
                id: 31,
                img:"/assets/restaurant/belgian waffle.avif",
                alt:"belgian waffle.avif",
                title:"The Belgian Waffle Co.",
                overlay:"",
                rating:4.6,
                timing:"60-65",
                food:" Waffle, Desserts, Ice Cream, Beverages",
                locality:" Mohan Nagar"
               },
               {
                id: 32,
                img:"/assets/restaurant/apni chapathi.avif",
                alt:"apni chopati.avif",
                title:"Apni Chopati",
                overlay:"",
                rating:4.5,
                timing:"60-65",
                food:"Snacks, Burgers, Pizzas, Fast Food",
                locality:"Rautha Wada"
               },
               {
                id: 33,
                img:"/assets/restaurant/baba chaines.avif",
                alt:"baba chaines.avif",
                title:"BABA CHAINES",
                overlay:"₹50 OFF ABOVE ₹349",
                rating:3,
                timing:"50-55",
                food:"Indian, Juices, Street Food, Pastas, Fast Food, Cafe",
                locality:"Chhindwara City"
               },
               {
                id: 34,
                img:"/assets/restaurant/fresh meals.avif",
                alt:"fresh meals.avif",
                title:"Fresh Meal's",
                overlay:"",
                rating:4.2,
                timing:"70-75",
                food:"North Indian, South Indian",
                locality:"Chhindwara City"
               },
               {
                id: 35,
                img:"/assets/restaurant/foodies cafeteria.avif",
                alt:"foodies cafeteria.avif",
                title:"Foodies Cafeteria",
                overlay:"",
                rating:false,
                timing:"55-60",
                food:"North Indian, South Indian",
                locality:"Chhindwara City"
               },
               {
                id: 36,
                img:"/assets/restaurant/chatori food.avif",
                alt:"chatori food.avif",
                title:"Chatori Food Junction",
                overlay:"₹125 OFF ABOVE ₹249",
                rating:5,
                timing:"55-60",
                food:"South Indian, Snacks, Pizzas, Burgers",
                locality:"Parasia Road"
               },
               {
                id: 37,
                img:"/assets/restaurant/rich table.avif",
                alt:"rich table.avif",
                title:"Rich Table Restaurant N Cafe",
                overlay:"25% OFF UPTO ₹65",
                rating:4.4 ,
                timing:"50-55",
                food:"North Indian, South Indian, Chinese, Beverages, Fast Food, Desserts",
                locality:"Chhindwara Locality"
               },
               {
                id: 38,
                img:"/assets/restaurant/madhun cafe.avif",
                alt:"madhuban cafe.avif",
                title:"Madhuban Cafe",
                overlay:"25% OFF UPTO ₹65",
                rating:false ,
                timing:"50-55",
                food:"Beverages, Street Food, Snacks, Pizzas, Pastas, Fast Food, Burgers, Cafe",
                locality:"Chhindwara City"
               },
               {
                id: 39,
                img:"/assets/restaurant/cafe ciao.avif",
                alt:"cafe ciao.avif",
                title:"CAFE CIAO BELLA",
                overlay:"",
                rating:false ,
                timing:"50-55",
                food:"Beverages, Street Food, Snacks, Pizzas, Pastas, Fast Food, Burgers, Cafe",
                locality:"Chhindwara City"
               },
               {
                id: 40,
                img:"/assets/restaurant/shree balaji.avif",
                alt:"shree balaji.avif",
                title:"Shree balaji chineese center",
                overlay:"",
                rating:false ,
                timing:"45-50",
                food:"Chinese",
                locality:"Chhindwara City"
               },
               {
                id: 41,
                img:"/assets/restaurant/famous dum biriyani.avif",
                alt:"famous dum biriyani.avif",
                title:"Famous Dum Biryani",
                overlay:"",
                rating:false ,
                timing:"55-60",
                food:"Biryani, North Indian, Chinese, Fast Food",
                locality:"Chhindwara City"
               },
               {
                id: 42,
                img:"/assets/restaurant/cafe 4 u.avif",
                alt:"cafe 4 u.avif",
                title:"Cafe 4 You",
                overlay:"10% OFF UPTO ₹40",
                rating:4.5,
                timing:"55-60",
                food:"Fast Food, Chinese, Beverages",
                locality:"Chhindwara City"
               },
               {
                id: 43,
                img:"/assets/restaurant/cafe 4 u.avif",
                alt:"cafe 4 u.avif",
                title:"Cafe 4 You",
                overlay:"10% OFF UPTO ₹40",
                rating:3.7,
                timing:"45-50",
                food:"Fast Food, Chinese, Beverages",
                locality:"Chhindwara City"
               },
               {
                id: 44,
                img:"/assets/restaurant/yummy better.avif",
                alt:"cafe 4 u.avif",
                title:"Yummy Better",
                overlay:"10% OFF UPTO ₹40",
                rating:4.1,
                timing:"50-55",
                food:"South Indian, Fast Food",
                locality:"Chhindwara City"
               },
               {
                id: 45,
                img:"/assets/restaurant/new radhey.avif",
                alt:"new radhey.avif",
                title:"New Radhey Shyam Choule Bhature Delhi Wala",
                overlay:"10% OFF UPTO ₹40",
                rating:2.9,
                timing:"55-60",
                food:"Snacks, Chinese",
                locality:"Mohan Nagar"
               },
               {
                id: 46,
                img:"/assets/restaurant/vicky chinese.avif",
                alt:"vicky chinese.avif",
                title:"Vicky Chinese Center",
                overlay:"₹125 OFF ABOVE ₹249",
                rating:false,
                timing:"50-55",
                food:"Chinese",
                locality:"Chhindwara City"
               },
               {
                id: 47,
                img:"/assets/restaurant/leafe town.avif",
                alt:"leafe town.avif",
                title:"Leaf Town Cafe",
                overlay:"",
                rating:false,
                timing:"55-60",
                food:"Cafe, Chinese, Fast Food, Pizzas",
                locality:"Chhindwara City"
               },
               {
                id: 48,
                img:"/assets/restaurant/cafe lemon.avif",
                alt:"cafe lemon.avif",
                title:"Cafe lemon chilli",
                overlay:"",
                rating:false,
                timing:"55-60",
                food:"Beverages, Street Food, Snacks, Pizzas, Waffle, Burgers, Cafe",
                locality:"Chhindwara City"
               },
               {
                id: 49,
                img:"/assets/restaurant/jain food.avif",
                alt:"jain food.avif",
                title:"Jain Food 4 You",
                overlay:"",
                rating:3.8,
                timing:"45-50",
                food:"North Indian",
                locality:"Chhindwara City"
               },
               {
                id: 50,
                img:"/assets/restaurant/sai nasta.avif",
                alt:"sai nasta.avif",
                title:"Sai Nasta And Food Corner",
                overlay:"",
                rating:false,
                timing:"55-60",
                food:"Chinese",
                locality:"Chhindwara City"
               },
               {
                id: 51,
                img:"/assets/restaurant/feelin shawarma.avif",
                alt:"feelin shawarma.avif",
                title:"Feelin'Shawarma Chhindwara",
                overlay:"₹50 OFF ABOVE ₹199",
                rating:4.7 ,
                timing:"40-45",
                food:"Fast Food, Street Food, Beverages",
                locality:"Chhindwara City"
               },
               {
                id: 52,
                img:"/assets/restaurant/chatar patar.avif",
                alt:"chatar patar.avif",
                title:"Chatar Patar Daily Needs",
                overlay:"",
                rating:4 ,
                timing:"45-50",
                food:"Bakery",
                locality:"Chhindwara City"
               },
               {
                id: 53,
                img:"/assets/restaurant/bihar champion.avif",
                alt:"bihar champion.avif",
                title:"Bihar Champion Litti Chokha",
                overlay:"",
                rating:false ,
                timing:"55-60",
                food:"Bihari, Desserts, Indian",
                locality:"Mohan Nagar"
               },
               {
                id: 54,
                img:"/assets/restaurant/guddu chinese.avif",
                alt:"guddu chinese.avif",
                title:"Guddu Chinese Centre",
                overlay:"",
                rating:5 ,
                timing:"55-60",
                food:"Chinese",
                locality:"Vishnu Nagar"
               },
               {
                id: 55,
                img:"/assets/restaurant/pizza boost.avif",
                alt:"pizza boost.avif",
                title:"Pizza Boost",
                overlay:"",
                rating:3.4 ,
                timing:"45-50",
                food:"Italian-American, Fast Food",
                locality:"Chhindwara Locality"
               },
               {
                id: 56,
                img:"/assets/restaurant/magic momo.avif",
                alt:"magic momo.avif",
                title:"Magic Momo",
                overlay:"",
                rating:3.7 ,
                timing:"55-60",
                food:"Momos, Chinese",
                locality:"Prasia Road"
               },
               {
                id: 57,
                img:"/assets/restaurant/chingchong momo.avif",
                alt:"chingchong momo.avif",
                title:"Chingchong Momo",
                overlay:"15% OFF ABOVE ₹1099",
                rating:4.7 ,
                timing:"60-65",
                food:"Momos, Chinese",
                locality:"Prasia Road"
               },
               {
                id: 58,
                img:"/assets/restaurant/omi ki bakery.avif",
                alt:"omi ki bakery.avif",
                title:"Omi Ki Bakery",
                overlay:"",
                rating:4.6 ,
                timing:"45-50",
                food:"Bakery",
                locality:"Chhindwara City"
               },
               {
                id: 59,
                img:"/assets/restaurant/myfit meals.avif",
                alt:"myfit meals.avif",
                title:"Myfit Meals - Meal Prep Co.",
                overlay:"₹50 OFF ABOVE ₹199",
                rating:4.7 ,
                timing:"55-60",
                food:"Continental, Salads",
                locality:"Chhindwara Locality"
               },
              ]
              )
}
